### ISSUE TITLE
Issue with peer join channel on Minikube

### ISSUE THREAD

**Issue by yinwhm12** [aidtechnology/hgf-k8s-workshop#10]
Sorry to trouble you again!
I had followed the hgf-k8s-workshop/dev_example's README.md to make one Orderer and one Peer fabric-network many times, but failed again. Unfortunately, I can't find the key to the trouble. it still threw the same error:
![image](https://user-images.githubusercontent.com/25929417/52160821-fb36e580-26f6-11e9-97be-1f00f2fe2356.png)
And I run the command "peer channel list" in the peer container, it also threw the same error.

So please give me a hand, and Thank you very much!

**Comment by yinwhm12** [comment]
The config yaml is yours you had shown in dev_example, and the values yaml does.

**Comment by alexvicegrab** [comment]
Hi @yinwhm12

Please make sure you have deleted and purged the Helm chart deployments first and also removed all associated secrets and volumes (if you are using a non-pproduction environment you can delete the namespaces `cas`, `orderers` and `peers`)

Thanks,
Sasha

**Comment by alexvicegrab** [comment]
If you have existing secrets from other CAs, it is likely you will have issues with deploying.

**Comment by yinwhm12** [comment]
I am sorry to tell you that I failed again. I had cleared the namespaces orderers and peers, and removed all associated secrets and volumes and networks.
it still connected to peer1-hlf-peer:7051 unsuccessfully.

**Comment by yinwhm12** [comment]
my k8s is based on minikube(v0.32.0).

**Comment by alexvicegrab** [comment]
Hmm... I have not tested it on Minikube (it should still work, I expect), but we have extensively tested it on Azure cloud. I'd advise you to try deploying on a proper Kubernetes environment and see if that works at all.

It's very difficult to diagnose your issue without further information. You are using the latest master build and have not changed any of the files/configuration?

**Comment by yinwhm12** [comment]
I'm glad to tell you that it works on a proper Kubernetes environment I had built. my Orderer and Peer and CouchDB Charts version are 1.2.5, 1.2.4 and 1.0.5. 
Compared with two environments, it may not work on Minikube. And Not Changed any of the files/configurations.

**Comment by yinwhm12** [comment]
Maybe you have a try on Minikube in a case I had done in an improper way just followed your README.md shown.

**Comment by alexvicegrab** [comment]
Hi @yinwhm12, that's great to hear. I have not tested in Minikube yet but will endeavour to try at least for the dev example as soon as I have some time to do so.

I'll add it as planned feature for Nephos, our open source library for deploying HLF networks: https://github.com/aidtechnology/nephos/issues/43

**Comment by alexvicegrab** [comment]
I am testing with minikube version: v0.34.1

Newest version is using CoreDNS rather than KubeDNS. Both are giving me issues. So it looks like an issue with the DNS service discovery on Minikube, similar to:

https://stackoverflow.com/questions/43152190/how-does-one-install-the-kube-dns-addon-for-minikube

**Comment by alexvicegrab** [comment]
I have managed to find a workaround, which will involve a small update to the Helm charts. Hopefully we will have Minikube support soon.

**Comment by alexvicegrab** [comment]
https://jira.hyperledger.org/browse/FAB-14305

**Comment by alexvicegrab** [comment]
Minikube now supported on `Nephos`, as described in the README.md here https://github.com/aidtechnology/nephos
