### ISSUE TITLE
Is it supported multiple organizations?

### ISSUE THREAD

**Issue by yinwhm12** [aidtechnology/hgf-k8s-workshop#11]
Hi, I wonder to know that your hgf-k8s-workshop/prod_example wether is supported by multiple organizations.

**Comment by alexvicegrab** [comment]
This example does not have multiple organisations, but it should be possible to do this, either by:
1) having organisations colocalised on a K8S cluster (but on different spaces separated by RBAC),
2) or by having organisations being located on different clusters and speaking to orderers located on one cluster,
3) or eventually having orderers and peers spread across clusters (possible in principle on https://github.com/bft-smart/fabric-orderingservice) but not yet implemented into Helm charts - help welcome.
