### ISSUE TITLE
Deploy Smart Contract

### ISSUE THREAD

**Issue by Vandersteen** [aidtechnology/hgf-k8s-workshop#14]
Do you have any suggestions (or best practices) to deploy a smart contract ?

* Manually
    * ?
* Using VS code extension
    * Port forwarding
    * Expose via ingress
    * ...

**Comment by alexvicegrab** [comment]
Hi Reinald @Vandersteen, this is a whole other can of worms.

The Workshop focuses on the network deployment aspect and the Chaincode deployment is a separate network administration beast alltogether.

Eventually we may tackle it in the `Nephos` library [here](https://github.com/aidtechnology/nephos), and contributions to it are very welcome, but it's not something I can address here (I am on the DevOps side, and less on the Chaincode).

Sorry to not be more helpful.

**Comment by nicolapaoli** [comment]
Hi @Vandersteen you have 2 ways of installing / interacting with Chaincode:
1) Using a cli to interact with your network (or manually, as you wrote)
2) Build an API using Fabric SDK to install/instantiate/invoke chaincode

I'd recommend the second option. You can use the SDK you prefer to build an API. Then you can deploy it to a pod to interact with the network created.

**Comment by Vandersteen** [comment]
@nicolapaoli Thank you for your tips, any chance you would have some examples laying around ?

I find alot of 'garbage' information on the net, but nothing helpfull really.

**Comment by Vandersteen** [comment]
After reading tons of documentation, blogs, ... I found a way to do exactly that

For future reference:

Manual way:

```
PEER_POD=$(kubectl get pods -n peers -l "app=hlf-peer,release=peer1" -o jsonpath="{.items[0].metadata.name}")

#Copy chaincode to pod
kubectl cp /path/to/chaincode peers/$PEER_POD:/tmp/chaincode

#Open shell in pod
kubectl exec -it -n peers $PEER_POD -- /bin/bash

#Install chaincode
CORE_PEER_MSPCONFIGPATH=$ADMIN_MSP_PATH peer chaincode install -n mychaincode -p /tmp/chaincode -l node -v 0.0.2

#Upgrade chaincode / change to install if it is the first time
CORE_PEER_MSPCONFIGPATH=$ADMIN_MSP_PATH peer chaincode upgrade -C mychannel -n mychaincode -l node -v 0.0.2 -c '{"Args": ["instantiate", "test"]}'
```

Same thing using the node-sdk (which could be run in a container or something like that, thx @nicolapaoli  for the tip)

```
// Create a new gateway for connecting to our peer node.
const gateway = new Gateway();
await gateway.connect(ccp, { wallet, identity: 'xxxx' });

const client = gateway.getClient();
const peers = client.getPeersForOrg('PeerMSP');

let installResponse = await client.installChaincode({
    targets: peers,
    chaincodePath: '/path/to/chaincode',
    chaincodeId: 'chaincode',
    chaincodeVersion: '0.0.2',
    chaincodeType: 'node',
    channelNames: ['mychannel']
});

let channel = client.getChannel('mychannel');

let proposalResponse = await channel.sendUpgradeProposal({
    targets: peers,
    chaincodeType: 'node',
    chaincodeId: 'chaincode',
    chaincodeVersion: '0.0.2',
    args: ['test'],
    fcn: 'instantiate',
    txId: client.newTransactionID()
});

console.log(proposalResponse);

console.log('Sending the Transaction ..');
const transactionResponse = await channel.sendTransaction({
    proposalResponses: proposalResponse[0],
    proposal: proposalResponse[1]
});

console.log(transactionResponse);
```
