### ISSUE TITLE
How to enable Ingress and TLS for orderer and peer?

### ISSUE THREAD

**Issue by mohammedrampurawala1111** [aidtechnology/hgf-k8s-workshop#15]
i've tried enabling ingress for orderer and peer by updating helm values for ord1.yaml,ord2.yaml and peer1.yaml
`ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/ssl-redirect: "true"
     nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
     certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
  path: /
  hosts:
    - host_name
  tls:
    - secretName: orderer-tls / peer-tls
      hosts:
       - host_name
`
ingress gets assigned to orderer and peer pods but i am not sure how to generate tls certs and key for them i've tried using 
`fabric-ca-client enroll -m host_name --enrollment.profile tls -d -u http://peer${NUM}:peer${NUM}_pw@localhost:7054 -M peer${NUM}_MSP` 
`fabric-ca-client enroll -m host_name --enrollment.profile tls  -d -u https://ord${NUM}:ord${NUM}_pw@localhost:7054 -M ord${NUM}_MSP`
it only generates tlscacerts which contains .pem file.  how to get .crt and .key file

**Comment by alexvicegrab** [comment]
Hi @Privet-mir, the TLS certs should be auto-generated via the cert-manager, particularly if you use the:

```
certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
```

**Comment by alexvicegrab** [comment]
At some point in the future we would like to have an example in the `nephos` library with Orderer/Peer ingresses. High quality outside PRs on this respect will be welcomed with open arms :)

**Comment by mohammedrampurawala1111** [comment]
Hi @alexvicegrab, thanks i've checked TLS certs are auto generated. i'm facing another issue after ingress is enabled for orderer and peer when i try to create channel it throws error saying 

> Error: ordering service endpoint orderer.hlf.example.com is not valid or missing
 
my orderer endpoint in configtx.yaml is 
> - orderer.hlf.example.com:7050
>  - orderer2.hlf.example.com:7050

when i checked ingress-controller logs it says

> W0314 10:59:08.459339       6 controller.go:842] Service "mainorg-peer/peer1-test" does not have any active Endpoint.
[logs.txt](https://github.com/aidtechnology/hgf-k8s-workshop/files/2966101/logs.txt)

i've attached ingress-controller logs, please check

**Comment by alexvicegrab** [comment]
If you use an ingress, the actual port exposed is 443 instead. So that's what should be in the `configtx.yaml`

```
orderer.hlf.example.com:443
orderer2.hlf.example.com:443
```

Same for peers, different notation.

**Comment by mohammedrampurawala1111** [comment]
@alexvicegrab as per your suggestions i've made changes in my configtx.yaml and after that i'm getting following error

> 2019-03-14 15:06:07.675 UTC [grpc] HandleSubConnStateChange -> DEBU 041 pickfirstBalancer: HandleSubConnStateChange: 0xc0003d0530, CONNECTING
2019-03-14 15:06:07.691 UTC [grpc] createTransport -> DEBU 042 grpc: addrConn.createTransport failed to connect to {orderer.hlf.example.com:443 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority". Reconnecting...
2019-03-14 15:06:07.691 UTC [grpc] HandleSubConnStateChange -> DEBU 043 pickfirstBalancer: HandleSubConnStateChange: 0xc0003d0530, TRANSIENT_FAILURE
Error: failed to create deliver client: orderer client failed to connect to orderer.hlf.example.com:443: failed to create new connection: context deadline exceeded

which certificates should i pass.
i've tried passing the certificates issued by cert manager by extracting them from secrets orderer-tls, peer-tls but it dose not seem to work.

**Comment by alexvicegrab** [comment]
You will need to provide the Let's Encrypt certificate as the Root CA certificate:

https://github.com/aidtechnology/hgf-k8s-workshop/blob/master/prod_example/config/Lets_Encrypt_Authority_X3.pem

**Comment by mohammedrampurawala1111** [comment]
Is this the write way to do it, because i'm still getting same error 
`kubectl  exec -n mainorg-peer $PEER_POD -- bash -c 'FABRIC_LOGGING_SPEC=debug peer channel create -o orderer.hlf.example.com:443 --tls --cafile /var/hyperledger/fabric_cfg/Lets_Encrypt_Authority_X3.pem -c mychannel -f /hl_config/channel/mychannel.tx'`

**Comment by alexvicegrab** [comment]
I don't think you have a `/var/hyperledger/fabric_cfg/Lets_Encrypt_Authority_X3.pem` file in the peer. If you saved it, it will have a different name, check where the secret is mounted on the `hlf-peer` chart, which will be a good exercise to understand where all elements are located and how (it will be in the `deployment.yaml` template)

**Comment by mohammedrampurawala1111** [comment]
Actually i just simply copied that file to the pod in that directory

**Comment by alexvicegrab** [comment]
Aha, that is also an option. More principled is to add it as a secret though:

```
            {{- if .Values.secrets.peer.tlsRootCert }}
            - mountPath: /var/hyperledger/tls/server/cert
              name: tls-rootcert
            {{- end }}
```

```
            {{- if .Values.secrets.ordTlsRootCert }}
            - mountPath: /var/hyperledger/tls/ord/cert
              name: ord-tls-rootcert
            {{- end }}
```

**Comment by alexvicegrab** [comment]
Not sure why you are seeing that error, but unfortunately I don't have time in the next few days to debug this, sorry.

In my own notes when enabling Ingresses, I have this:

```
kubectl exec -n peers $PEER_POD -- bash -c 'peer channel create -o ord0.orderers.hlfdev.aidtech-test.xyz:443 -c mychannel -f /hl_config/channel/mychannel.tx --tls --cafile $ORD_TLS_PATH/cacert.pem --certfile $CORE_PEER_TLS_CLIENTCERT_FILE --keyfile $CORE_PEER_TLS_CLIENTKEY_FILE --clientauth'
```

You will need to adapt this to your own needs, and this assumes you attached the relevant files as secrets, but hope this helps.

**Comment by mohammedrampurawala1111** [comment]
No problem, Thanks for the help. i'll try to debug it myself. but in case if it dose not work  i'll have to trouble you again.:)

**Comment by mohammedrampurawala1111** [comment]
I figured out the error, i was passing letsencrypt-staging Cluster Issuer  replaced it with letsencrypt-production. 

`ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/ssl-redirect: "true"
     nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
     certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
  path: /
  hosts:
    - orderer.hlf.example.com
  tls:
    - secretName: orderer-tls
      hosts:
        - orderer.hlf.example.com
`

same for orderer2 and peers, different notation

Now i bumped into this error while trying to create channel
`Error: rpc error: code = Internal desc = transport: received the unexpected content-type "text/html"
`

**Comment by mohammedrampurawala1111** [comment]
@alexvicegrab i'm receiving following error in orderer logs 
`grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams received bogus greeting from client: \"\\x16\\x03\\x01\\x00\\xc0\\x01\\x00\\x00\\xbc\\x03\\x03\\xef\\xbeS2\\x9c\\xc95\\x00\\x97\\x91\\x10}{\""`

**Comment by alexvicegrab** [comment]
Hi @Privet-mir,

The current workshop does not support external TLS, so I can't help with that here, as we don't have bandwidth to update the workshop.

However, there is a roadmap to support the TLS part, on Nephos (some 5-10 issues out of the 20ish listed here: https://github.com/hyperledger-labs/nephos/issues), but we need help from the community to contribute to the codebase.

If you'd like having a go at some of these issues, that would be very welcome, as we have limited bandwidth internally, having done a significant part of the automation work.

**Comment by yonghuigit** [comment]
Hi @Privet-mir
I've been playing with this as well. Please try to change protocol: "GRPCS" to protocol: "GRPC" and see if it works?

**Comment by mohammedrampurawala1111** [comment]
HI, @yonghuigit 
I've tried doing that it requires mutual TLS

**Comment by ashishxooa** [comment]
Hi @alexvicegrab 

I tried with "kubectl exec -n peers $PEER_POD -- bash -c 'peer channel create -o ord0.orderers.hlfdev.aidtech-test.xyz:443 -c mychannel -f /hl_config/channel/mychannel.tx --tls --cafile $ORD_TLS_PATH/cacert.pem --certfile $CORE_PEER_TLS_CLIENTCERT_FILE --keyfile $CORE_PEER_TLS_CLIENTKEY_FILE --clientauth'"

Still it doesn't work (I did change the orderer endpoint obviously). Without the tls, my network works fine. When I try to enable to tls. 

I get this in the orderer logs, while trying to create the channel. 

2019-05-07 13:48:17.896 UTC [core.comm] ServerHandshake -> ERRO 2d26 TLS handshake failed with error remote error: tls: bad certificate {"server": "PeerServer", "remote address": "127.0.0.1:45130"}
2019-05-07 13:48:18.896 UTC [core.comm] ServerHandshake -> ERRO 2d27 TLS handshake failed with error remote error: tls: bad certificate {"server": "PeerServer", "remote address": "127.0.0.1:45138"}

From you notes, you have a variable $ORD_TLS_PATH/cacert.pem, there was no file here so I copied the tls/client/cert/cacert.pem which is also the CORE_PEER_TLS_ROOTCERT_FILE. This file was created by the secret using lets-encrypt.pem file. 

Please can you throw some light here?

**Comment by alexvicegrab** [comment]
@ashishxooa, I suggest you look at the Nephos repository and check the roadmap of issues that can be contributed to to enable TLS. I won't have time to work on this in the coming months, and any contributions done should be to Nephos:

https://github.com/hyperledger-labs/nephos

**Comment by ricardoruanoc** [comment]
Hi, in my case I got this error 

`    [core.comm] ServerHandshake -> ERRO 025 TLS handshake failed with error remote error: tls: internal error {"server": "Orderer", "remote address": "190.22.189.42:40746"}`

When I use a fabric sdk to connect to a Fabric Network that use TLS enabled.
To solve this you need ensure that the connection profile use the hostnameOverride propertie in Orderer section this an example

_orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      hostnameOverride: orderer.example.com
      grpc-max-send-message-length: 15
      grpc.keepalive_time_ms: 360000
      grpc.keepalive_timeout_ms: 180000_

 

Please check the next example to more information : https://github.com/hyperledger/fabric-sdk-java/blob/master/src/test/fixture/sdkintegration/network_configs/network-config-tls.yaml

Really I was working days in this error and finally I found the solution

To more information, fabric training,  or develop blockchain solutions to the business and goverment   based in Hyperledger Fabric in Chile and Latin America please visit [https://www.blockchainempresarial.com](https://www.blockchainempresarial.com)

**Comment by mohammedrampurawala1111** [comment]
Hi @ricardoruanoc have you configured it using Nginx Ingress
