### ISSUE TITLE
Error while installing chaincode on Peer

### ISSUE THREAD

**Issue by rsbhardwaj** [aidtechnology/hgf-k8s-workshop#16]
Hi,
I am getting below error while installing chaincode on the peer in this.
Command -  kubectl exec $PEER_POD -n peers -- bash -c 'peer chaincode install -n mycc -v 1.0  -p /var/chaincode/'

Error - error getting chaincode code mycc: command <go env>: failed with error: "exec: "go": executable file not found in $PATH"
NOTE - I have placed the chaincode in the docker file system
Do I need to install GO in the peer container or machine, please suggest.
Thanks,

**Comment by mohammedrampurawala1111** [comment]
Hi, @rsbhardwaj  you are trying to install go chaincode from peer container and go env is not available on peer container. you need CLI container to do so. 

For CLI you need to create and deploy its helm chart. you can just do a bit of modification in peer helm chart just replace the image tag in helm chart with hyperledger/fabric-tools and your CLI would be ready. modify other env variables as required.

In case you want to test chaincode from peer you can try using node js chiancode. node env is supported on peer.

**Comment by rsbhardwaj** [comment]
Thanks @Privet-mir for help
Can u share reference config for cli if there is any.

**Comment by mohammedrampurawala1111** [comment]
@rsbhardwaj actually i'm a newbie in DevOps, i've tried creating CLI chart although it works and i've tested too, but its quite messed up.  I'll push it to my git repo and share the link as soon as possible.

**Comment by rsbhardwaj** [comment]
Sure @Privet-mir.
Just one query for heads up , how fabric-CLI communicates with the fabric peer in case of Kubernetes, via services or directly to the peer pod??

**Comment by rsbhardwaj** [comment]
Hi @Privet-mir,
I have deployed the fabric-cli in K8s and able to install the go chaincode on peer.
But while instantiating the chaincode I am getting below error-

Error: could not assemble transaction, err proposal response was not successful, error code 500, 
msg error starting container: error starting container: Failed to generate platform-specific docker build:
Error returned from build: 1 "can't load package: package ./github.com/chaincode: cannot find package "./github.com/chaincode" in:
        /github.com/chaincode

Did you get the same?

**Comment by mohammedrampurawala1111** [comment]
No, i didn't face this error in kubernetes.

**Comment by rsbhardwaj** [comment]
I have deployed CLI to Kubernetes.
Installed chaincode on peer from CLI
Instantiating the chaincode gives above error
logs of peer
- 2019-04-03 08:46:37.985 UTC [endorser] callChaincode -> INFO 0f1 [mychannel][b8fa6eea] Entry chaincode: name:"lscc" 
2019-04-03 08:46:38.006 UTC [chaincode.platform.golang] GenerateDockerBuild -> INFO 0f2 building chaincode with ldflagsOpt: '-ldflags "-linkmode external -extldflags '-static'"'
2019-04-03 08:46:38.832 UTC [chaincode.platform] func1 -> ERRO 0f3 Failed to generate platform-specific docker build: Error returned from build: 1 "can't load package: package ./github.com/chaincode: cannot find package "./github.com/chaincode" in:
        /github.com/chaincode
"
2019-04-03 08:46:38.832 UTC [dockercontroller] deployImage -> ERRO 0f4 Error building image: Failed to generate platform-specific docker build: Error returned from build: 1 "can't load package: package ./github.com/chaincode: cannot find package "./github.com/chaincode" in:
        /github.com/chaincode
"
2019-04-03 08:46:38.832 UTC [dockercontroller] deployImage -> ERRO 0f5 Build Output:
********************

********************
2019-04-03 08:46:38.840 UTC [endorser] callChaincode -> INFO 0f6 [mychannel][b8fa6eea] Exit chaincode: name:"lscc"  (854ms)
2019-04-03 08:46:38.840 UTC [endorser] SimulateProposal -> ERRO 0f7 [mychannel][b8fa6eea] failed to invoke chaincode name:"lscc" , error: Failed to generate platform-specific docker build: Error returned from build: 1 "can't load package: package ./github.com/chaincode: cannot find package "./github.com/chaincode" in:
        /github.com/chaincode
"
error starting container
error starting container
2019-04-03 08:46:38.840 UTC [comm.grpc.server] 1 -> INFO 0f8 unary call completed {"grpc.start_time": "2019-04-03T08:46:37.985Z", "grpc.service": "protos.Endorser", "grpc.method": "ProcessProposal", "grpc.peer_address": "10.44.2.8:36140", "grpc.code": "OK", "grpc.call_duration": "855.13149ms"}

**Comment by mohammedrampurawala1111** [comment]
@rsbhardwaj, I'm not sure why you are getting this error but I've pushed charts to my repository. 

https://github.com/Privet-mir/hlf-kafka-k8s.git

I've also created a script which will install all charts on your cluster  and also install and instantiate  sample chaincode on peer using Fabric CLI as well as query it.

Just make sure ingress-controller, cert-manager and cluster issuers are installed on your cluster before running this script and your DNS is pointing to external ip of ingress.

change host in prod_example/helm_values/ca.yaml

to run script goto 
cd prod_example
./example_kafka.sh 

Fabric CLI chart is very messed up and not clean.
But hope this might help you.

I'll suggest before running this you should clean up your k8s cluster or purge it and deploy new one

**Comment by rsbhardwaj** [comment]
Thanks I will look into it....
The above error was related to relative paths .... resolved it...
All cool ... :)

**Comment by rsbhardwaj** [comment]
hey @Privet-mir ,
Have you tried connecting to fabric K8s cluster from SDK?
Actually I want to understand how you exposed the peer and peer services to outside K8s so that client application can consume it and send grpc calls?
Thanks

**Comment by mohammedrampurawala1111** [comment]
@rsbhardwaj You can use Load Balancer or Node Port or Ingress in K8's to expose your service outside cluster, I've used Load Balancer with static IP to expose my service outside K8's cluster.

**Comment by rsbhardwaj** [comment]
yeah right, I have also done the same but getting below error while trying to query the chaincode using fabric-SDK.
"error: [Remote.js]: Error: Failed to connect before the deadline URL:grpc://IP:7051
Do I have to done anything else for the load-balancer to accept grpc requests ??

**Comment by mohammedrampurawala1111** [comment]
You don't have to do anything else, i'm not sure why you are getting this error. it would be better if  you try to share more logs from peer pod

**Comment by rsbhardwaj** [comment]
There is nothing in peer logs related to this.
Can u share with me your LoadBalancer service configuration ?

**Comment by mohammedrampurawala1111** [comment]
I've just declared
service:
    type: LoadBalancer

Well this will differ when you want to deploy load balancer with static IP.
You can also share the steps you followed so that i can reproduce on my end.

**Comment by rsbhardwaj** [comment]
yeah, mine is resolved firewall was blocking it ,,,,,, created rule for that.
Thanks @Privet-mir lets connect on rocket chat - my id - @heyjames

**Comment by mohammedrampurawala1111** [comment]
@rsbhardwaj  sure i'll ping you.
