### ISSUE TITLE
Add incubator repository

### ISSUE THREAD

**Issue by easeev** [aidtechnology/hgf-k8s-workshop#7]
By default, Helm doesn't seem to enable the `incubator` repository, which is used in [this step](https://github.com/aidtechnology/hgf-k8s-workshop/tree/master/prod_example#kafka-for-ordering-service).

The suggestion is to add the following line either after `helm init` or before installing kafka chart:
`helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/`

**Comment by alexvicegrab** [comment]
Good point! Will fix soon :)

**Comment by alexvicegrab** [comment]
Addressed in #9

**Comment by nicolapaoli** [comment]
Closing this issue as it was merged in #9
