### ISSUE TITLE
Clean up namespaces

### ISSUE THREAD

**Issue by easeev** [aidtechnology/hgf-k8s-workshop#8]
In the [last step](https://github.com/aidtechnology/hgf-k8s-workshop/tree/master/prod_example#deleting) of `prod_example` it will be good to clean up namespaces as well:

`kubectl delete namespace cas cert-manager ingress-controller orderers peers`

**Comment by alexvicegrab** [comment]
Good point, we probably can keep the cert-manager and ingress-controller, as these can be used for other applications, but will add the cleaning up of the namespaces to the description.

**Comment by alexvicegrab** [comment]
Addressed in #9

**Comment by nicolapaoli** [comment]
Closing this issue as it was merged in #9
